/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#f9f9ff",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#00497c",
        "on-primary-fixed": "#00201f",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#004f52",
        "outline": "#6e7978",
        "secondary": "#1c619c",
        "surface-dim": "#cfdaf1",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#98f2ef",
        "surface-container-low": "#f0f3ff",
        "on-tertiary": "#ffffff",
        "on-surface": "#111c2c",
        "secondary-fixed": "#d1e4ff",
        "on-background": "#111c2c",
        "secondary-container": "#83bdfd",
        "tertiary": "#006164",
        "surface-container-high": "#dee8ff",
        "surface": "#f9f9ff",
        "on-tertiary-container": "#cafdff",
        "primary": "#006160",
        "on-surface-variant": "#3e4948",
        "tertiary-fixed": "#73f6fb",
        "surface-container-highest": "#d8e3fa",
        "on-secondary": "#ffffff",
        "outline-variant": "#bdc9c8",
        "surface-container": "#e7eeff",
        "tertiary-fixed-dim": "#52d9de",
        "primary-fixed-dim": "#7bd5d2",
        "inverse-primary": "#7bd5d2",
        "surface-bright": "#f9f9ff",
        "on-tertiary-fixed": "#002021",
        "secondary-fixed-dim": "#9ecaff",
        "on-primary-fixed-variant": "#00504e",
        "tertiary-container": "#007c80",
        "on-secondary-fixed": "#001d36",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#ebf1ff",
        "inverse-surface": "#263142",
        "on-secondary-container": "#004c80",
        "on-error": "#ffffff",
        "primary-container": "#0d7c7a",
        "on-primary-container": "#c2fffc",
        "error-container": "#ffdad6",
        "surface-variant": "#d8e3fa",
        "surface-tint": "#006a68"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "1.25rem",
        "space-md": "1rem",
        "space-sm": "0.5rem",
        "margin": "3rem",
        "gutter-mobile": "1rem",
        "gutter": "1.5rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem"
      },
      fontFamily: {
        "display-hero-mobile": ["Epilogue", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "headline-md": ["Epilogue", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "display-hero": ["Epilogue", "sans-serif"],
        "title-md": ["Manrope", "sans-serif"],
        "body-sm": ["Manrope", "sans-serif"],
        "headline-sm": ["Epilogue", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "headline-lg": ["Epilogue", "sans-serif"],
        "headline-lg-mobile": ["Epilogue", "sans-serif"]
      },
      fontSize: {
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["22px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}